handle FileNotFoundError in parse_requirements function
bndr/pipreqs pull request #397
Opened 2023-10-02 21:13 UTC by mateuslatrova

When the function "parse_requirements.txt" does not find the file passed as a parameter, it just raises an OSError.

This PR changes that behavior. Now, when that happens, this function handles it by printing a helpful message to the user and ends the program execution immediately.

2023-10-04 12:22 UTC, fredgrub commented
This PR is related to PR https://github.com/bndr/pipreqs/pull/392. Since this PR modifies the functioning of the 'parse_requirements' function, we must accept it first.

2023-10-04 17:35 UTC, alan-barzilay commented
LGTM just remove the white trailing space please

2023-10-04 17:35 UTC, alan-barzilay commented
ah, and rebase, thx

2023-10-09 20:24 UTC, mateuslatrova commented
@alan-barzilay rebased and fixed the white trailing space.

2023-10-10 18:40 UTC, alan-barzilay requested changes

2023-10-10 18:40 UTC, alan-barzilay commented on tests/test_pipreqs.py
> +    @patch("sys.exit")
reviewdog is complaining here

2023-10-10 18:40 UTC, alan-barzilay commented on pipreqs/pipreqs.py
> +        out_file.write(
please stop changing formatting and quotes convention on every commit you guys do haha

2023-10-19 23:20 UTC, mateuslatrova commented on tests/test_pipreqs.py
> +    @patch("sys.exit")
solved

2023-10-20 11:59 UTC, alan-barzilay approved these changes

2023-10-20 11:59 UTC, merged