Implementing darker as pre-commit
bndr/pipreqs pull request #421
Opened 2023-11-27 20:27 UTC by willianrocha

- applying pep8 rules
- delete unused function "filter_line"
- fix return type on docs
- create test for output_requirements
- add "copy to clipboard icon" in installation section - Based on PR #369 and #396 - Authors Muhammad-Aadil and mateuslatrova
- add test for "compare_modules" function
- add test for parse_requirements function
- Bump wheel from 0.23.0 to 0.38.1
- CI: Add Python 3.10 and 3.11, update actions, run on pushes and manually
- Specify pypy version - The pypy v7.3.13, used by GitHub Actions, was failing. So I force to use pypy v7.3.12 that was passing. - The original PR was done by @EwoutH at #334 and modified by @willianrocha at #398.
- handle FileNotFoundError in parse_requirements function
- Migrating the packaging system to `poetry` with `pyproject.toml` - Deleted old setup files `requirements.txt`, `setup.cfg`, `setup.py`, `MANIFEST.in` - Added poetry files `poetry.toml`, `pyproject.toml`, `poetry.lock` - Added `.pyenv-version` and `.tool-versions` for `pyenv` and `asdf` - Updated `Makefile`, `CONTRIBUTING.rst`, `tox.ini`
- Bump python 3.12 support
- Blacker WIP

2023-12-10 22:52 UTC, willianrocha commented
In flynt 0.68, some breaking changes were introduced as states in darker release notes [1.7.1](https://github.com/akaihola/darker/blob/master/CHANGES.rst#171---2023-03-26)

2023-12-11 20:06 UTC, mateuslatrova commented
Hey @willianrocha!

1. There are some merge conflicts, so I guess this branch needs rebasing.

2. It seems to me that most of the changes were related to formatting (correct me if I'm wrong). Since the important changes don't include many code/configuration changes and not all commits have a working version of the feature, maybe you could reduce the number of commits to one or two(which would be working versions), and describe any important information(like the breaking changes from flynt) in the commits' description.

3. When I run `git commit -m 'test'`, I receive the following error: `FileNotFoundError: [Errno 2] No such file or directory: 'flake8'`. Then I ran the same command with poetry: `poetry run git commit -m 'test'` and it worked. Is this the expected behavior? It does not seem so intuitive. But if it stays like this, I guess it should be documented in the `CONTRIBUTING.rst` file.

2023-12-11 22:00 UTC, alan-barzilay commented on CONTRIBUTING.rst
> +    $ poetry run pre-commit install
can' t this be done in the `poetry install --with dev` step somehow?

2023-12-11 22:02 UTC, alan-barzilay commented on CONTRIBUTING.rst
> +    $ poetry run pre-commit install
since pre commit is already marked as a dependency, do we need this? or is it installing the hooks and not  package pre-commit?

2023-12-11 22:08 UTC, alan-barzilay requested changes
I make matheus words my own, good work but the commit messages need deeper explanations and justifications for the choices made. I agree everything could be one or 2 commits, maybe one for the new files and the second one with the changes made by applying the pre-commit.

Since there is that issue with flynt and blacker, I assume there is no better alternative, right? I guess we gotta live with that weird version exigence haha

2023-12-11 22:08 UTC, alan-barzilay commented on .pre-commit-config.yaml
> +          - isort==5.9
why this versions exactly?

2023-12-11 22:08 UTC, alan-barzilay commented on pyproject.toml
> +/(
whats the difference between this and the old format? it was more readable/pythonic, was it broken?

2023-12-12 16:02 UTC, alan-barzilay commented
> When I run git commit -m 'test', I receive the following error: FileNotFoundError: [Errno 2] No such file or directory: 'flake8'. Then I ran the same command with poetry: poetry run git commit -m 'test' and it worked. Is this the expected behavior? It does not seem so intuitive. But if it stays like this, I guess it should be documented in the CONTRIBUTING.rst file.

forgot to emphasize this one, git commit failing is not acceptable behaviour haha

2024-02-18 18:17 UTC, closed without merging